import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

describe("早稻田個人打席格的球性與傳接分區", () => {
  it("以單一紙本方格、菱形虛線與必要導引呈現打席格，並把 E／FO／GO、球性方向及守備傳接固定於右下", () => {
    const source = readFileSync(resolve(process.cwd(), "components/baseball/waseda-personal-record-cell.tsx"), "utf8");

    expect(source).toContain('type: "GO"');
    expect(source).toContain('type: "FO"');
    expect(source).toContain("const battedBallOuterMark");
    expect(source).toContain("battedBallRightBottom: {");
    expect(source).toContain("const lowerRight");
    expect(source).toContain("styles.rightBottom");
    expect(source).toContain("const safeInnerOverride");
    expect(source).toContain("const innerMark");
    expect(source).toContain("styles.innerMark");
    expect(source).toContain("battedBallOuterMark");
    expect(source).toContain("lowerRight");
    expect(source).toContain("const allowedInnerMarks");
    expect(source).toContain("styles.outerArea");
    expect(source).toContain("diamondStage");
    expect(source).toContain("diamondGuideTop");
    expect(source).toContain("diamondGuideRight");
    expect(source).toContain("innerSquare");
    expect(source).toContain('outerArea: { flex: 1, minHeight: 96, position: "relative", overflow: "hidden"');
    expect(source).toContain('innerSquare: { width: 26, height: 26, alignItems: "center", justifyContent: "center", backgroundColor: "transparent" }');
    expect(source).toContain('diamondStage: { position: "absolute", top: "50%", left: "50%", width: 68, height: 68');
    expect(source).not.toContain("diamondFrame");
    expect(source).toContain('diamond: { position: "absolute", width: 32, height: 32, borderWidth: 1, borderStyle: "dashed"');
    expect(source).toContain('compact: { width: 92, minWidth: 92, minHeight: 70 }');
    expect(source).toContain('pitchColumnCompact: { width: 22');
    expect(source).toContain('outerAreaCompact: { minHeight: 68, borderWidth: 0 }');
    expect(source).toContain('緊湊格維持 68px 高的單一紙本方格，不加內嵌外框');
    expect(source).toContain('wrap: { borderWidth: 1, borderColor: COLORS.line, backgroundColor: COLORS.white, overflow: "hidden" }');
    expect(source).not.toContain("diamondFrame");
    expect(source).toContain("const correctedBattedBallParts");
    expect(source).toContain("const hasStructuredOuterCorrection");
    expect(source).toContain("battedBallRightBottom");
    expect(source).toContain("outerMarks?.rightBottom ?? lowerRight");
    expect(source).toContain("getCompactBattedBallNotation");
    expect(source).toContain("POSITION_NAME_TO_SCOREBOOK_NUMBER");
    expect(source).toContain('mark.type === "GO" ? "＿" : mark.type === "FO" ? "⌒" : mark.type');
    expect(source).toContain("getCompactScorebookRoute");
    expect(source).toContain("右下角簡化符號：${compactBattedBallNotation}");
    expect(source).toContain("rightBottom: { position: \"absolute\", right: 3, bottom: 3");
    expect(source).toContain("zIndex: 8");
    expect(source).toContain("rightBottomHasFielding");
    expect(source).toContain("getFieldingNotationDisplay");
    expect(source).toContain("fieldingCharacterLimit");
    expect(source).toContain("fieldingLineLimit");
    expect(source).toContain("numberOfLines={fieldingLineLimit}");
    expect(source).toContain("fieldingTapTarget");
    expect(source).toContain("setIsFieldingNotationOpen(true)");
    expect(source).toContain("右下角傳接區");
    expect(source).toContain("唯讀放大檢視；不會變更逐球、跑壘、比分或正式統計");
    expect(source).toContain("useFieldingNotationPreferences");
    expect(source).toContain("const { fontSize: fieldingNotationFontSize }");
    expect(source).toContain("文字大小");
    expect(source).toContain("開啟閱讀偏好");
    expect(source).toContain('router.push("/reading-preferences")');
    expect(source).toContain("getFieldingNotationFontMetrics(fieldingNotationFontSize)");
    expect(source).toContain("replacementBadge?: ScorebookSubstitutionBadge");
    expect(source).toContain("pitchingChangeBadge?: ScorebookPitchingChangeBadge");
    expect(source).toContain("換投標記：第${pitchingChangeBadge.inning}局 ︺ P");
    expect(source).toContain("styles.pitchingChangeBadge");
    expect(source).toContain('pitchingChangeBadge: { position: "absolute", top: 3, left: 4');
    expect(source).toContain("替換交接：第${replacementBadge.inning}局起 ${replacementBadge.code}");
    expect(source).toContain("const replacementHandoffPitchNumber");
    expect(source).toContain("const replacementHandoffLabel");
    expect(source).toContain('replacementHandoffPitchNumber === 0 ? "打席開始交接"');
    expect(source).toContain("`第 ${replacementHandoffPitchNumber} 球交接`");
    expect(source).toContain("const replacementPitchTotal = replacementBadge");
    expect(source).toContain("本席 {replacementPitchTotal} 球");
    expect(source).toContain("非精確交接");
    expect(source).toContain("styles.replacementBadge");
    expect(source).toContain('replacementBadge: { position: "absolute", top: 3, left: "50%"');
    expect(source).toContain("replacementBadgeCode");
    expect(source).toContain("replacementBadgeHandoff");
    expect(source).toContain("replacementBadgePitchCount");
    expect(source).toContain("zIndex: 12");
    expect(source).toContain('rightBottom: { position: "absolute", right: 3, bottom: 3');
    expect(source).toContain("rightBottomHasFielding");
    expect(source).toContain('replacementBadge: { position: "absolute", top: 3, left: "50%"');
    expect(source).toContain("const SCOREBOOK_GLYPH_MINIMUM_FONT_SCALE = 0.35");
    expect(source).toContain("const scorebookGlyphFitProps");
    expect(source).toContain("adjustsFontSizeToFit: true");
    expect(source).toContain("minimumFontScale: SCOREBOOK_GLYPH_MINIMUM_FONT_SCALE");
    expect(source).toContain("<Text {...scorebookGlyphFitProps} key={`${mark}-${index}`} numberOfLines={1}");
    expect(source).toContain("<Text {...scorebookGlyphFitProps} numberOfLines={2} style={[styles.leftTop");
    expect(source).toContain("batterFirstBaseMark : styles.rightTop");
    expect(source).toContain("styles.compactBattedBallNotation");
    expect(source).toContain("<Text {...scorebookGlyphFitProps} ellipsizeMode=\"tail\" numberOfLines={fieldingLineLimit}");
    expect(source).toContain("<Text {...scorebookGlyphFitProps} numberOfLines={1} style={[styles.innerMark");
    expect(source).toContain("<Text {...scorebookGlyphFitProps} numberOfLines={1} style={[styles.runnerAdvanceLabel");
    expect(source).toContain("runnerSegmentStyle(line.segment)");
    expect(source).toContain("runnerHomeToFirst");
    expect(source).toContain('backgroundColor: "transparent"');
    expect(source).toContain('const batterReachesFirst = finalResult === "BB" || finalResult === "HBP" || finalResult === "E" || droppedThirdStrike');
    expect(source).toContain("const batterFirstBaseLines = batterReachesFirst");
    expect(source).toContain("getRunnerAdvanceLines({ result: finalResult, modifiers })");
    expect(source).toContain("batterFirstBaseLines.map((line) => (");
    expect(source).toContain("styles.batterReachLine, batterReachSegmentStyle(line.segment)");
    expect(source).toContain("const runnerAdvanceLines = runnerAdvanceContexts");
    expect(source).toContain("function batterReachSegmentStyle(segment: HitAdvanceSegment)");
    expect(source).toContain("batterFirstBaseMark: { position: \"absolute\", right: 4, bottom: 15");
    expect(source).toContain("runnerAdvanceLine: { position: \"absolute\", width: 32, height: 2.5");
    expect(source).toContain("batterReachLine: { position: \"absolute\", width: 48, height: 3");
    expect(source).toContain("runnerHomeToFirst: { left: 29, top: 44, transform: [{ rotate: \"-45deg\" }]");
    expect(source).toContain("hitHomeToFirst: { left: 27, top: 50, transform: [{ rotate: \"-45deg\" }]");
    expect(source).toContain("runnerAdvanceContexts = (runnerAdvance ? [runnerAdvance] : syncedRunnerAdvances)");
    expect(source).toContain("runnerSegmentStyle(line.segment)");
  });
});
